# Generated by Django 2.1.3 on 2018-12-12 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20181210_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='main_post',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Post'),
        ),
    ]
