# Generated by Django 2.1.4 on 2018-12-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture_url',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
